// ******************************
// PRODUCT ARRAY
// ******************************
let product = [
  {
    "basketArrayPos": null,
    "name": "Thick Sliced Ham",
    "cost": 3.00,
    "onsale": false,
    "stock": 15,
    "category": "meat",
    "image": `<i class="fas fa-image fa-5x"></i>`,
  },
  {
    "basketArrayPos": null,
    "name": "Brewers Wheats Cereal",
    "cost": 1.79,
    "onsale": true,
    "stock": 1,
    "category": "cereals",
    "image": `<i class="fas fa-image fa-5x"></i>`,
  },
  {
    "basketArrayPos": null,
    "name": "Individual Baby Potato",
    "cost": 0.09,
    "onsale": false,
    "stock": 300,
    "category": "veg",
    "image": `<i class="fas fa-image fa-5x"></i>`,
  },
  {
    "basketArrayPos": null,
    "name": "Individual Carrot",
    "cost": 0.07,
    "onsale": false,
    "stock": 265,
    "category": "veg",
    "image": `<i class="fas fa-image fa-5x"></i>`,
  },
  {
    "basketArrayPos": null,
    "name": "Individual Parsnip",
    "cost": 0.07,
    "onsale": false,
    "stock": 604,
    "category": "veg",
    "image": `<i class="fas fa-image fa-5x"></i>`,
  },
  {
    "basketArrayPos": null,
    "name": "Whole Lettuce",
    "cost": 0.31,
    "onsale": true,
    "stock": 124,
    "category": "veg",
    "image": `<i class="fas fa-image fa-5x"></i>`,
  },
  {
    "basketArrayPos": null,
    "name": "Individual Onion",
    "cost": 0.25,
    "onsale": false,
    "stock": 540,
    "category": "veg",
    "image": `<i class="fas fa-image fa-5x"></i>`,
  },
  {
    "basketArrayPos": null,
    "name": "Waffer Thin Ham",
    "cost": 1.50,
    "onsale": true,
    "stock": 36,
    "category": "meat",
    "image": `<i class="fas fa-image fa-5x"></i>`,
  },
  {
    "basketArrayPos": null,
    "name": "Norburtons Thick Bread",
    "cost": 1.05,
    "onsale": false,
    "stock": 204,
    "category": "bakery",
    "image": `<i class="fas fa-image fa-5x"></i>`,
  },
  {
    "basketArrayPos": null,
    "name": "French Frenzy Croissants",
    "cost": 2.30,
    "onsale": false,
    "stock": 36,
    "category": "bakery",
    "image": `<i class="fas fa-image fa-5x"></i>`,
  },
  {
    "basketArrayPos": null,
    "name": "Norburton's Thin Bread ",
    "cost": 0.99,
    "onsale": true,
    "stock": 36,
    "category": "bakery",
    "image": `<i class="fas fa-image fa-5x"></i>`,
  },
  {
    "basketArrayPos": null,
    "name": "Gardener's Patch - Carrot Pack",
    "cost": 1.50,
    "onsale": false,
    "stock": 110,
    "category": "veg",
    "image": `<i class="fas fa-image fa-5x"></i>`,
  },
  {
    "basketArrayPos": null,
    "name": "Gardener's Patch - Baby Potatos",
    "cost": 1.50,
    "onsale": false,
    "stock": 86,
    "category": "veg",
    "image": `<i class="fas fa-image fa-5x"></i>`,
  },
  {
    "basketArrayPos": null,
    "name": "Smocopops",
    "cost": 1.25,
    "onsale": true,
    "stock": 23,
    "category": "cereal",
    "image": `<i class="fas fa-image fa-5x"></i>`,
  },
  {
    "basketArrayPos": null,
    "name": "Slice Crispies",
    "cost": 2.50,
    "onsale": false,
    "stock": 106,
    "category": "cereal",
    "image": `<i class="fas fa-image fa-5x"></i>`,
  },
  {
    "basketArrayPos": null,
    "name": "Growers Harvest Orange Juice",
    "cost": 3.99,
    "onsale": false,
    "stock": 10,
    "category": "juices",
    "image": `<i class="fas fa-image fa-5x"></i>`,
  },
];